import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import TopNav from "@/components/TopNav";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={cn("", inter.className)}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
				>
					<TopNav />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
